
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "optparse.h"

struct opt_str scriptstr;
int flags[7];
int opt_level;
int tab_level;
const char *divchoices[] = {"old", "warn", "warnall", "new", NULL};

#define MAXW 10
int nW, Wactions[MAXW];
char *Wtails[MAXW];
const char *Wchoices[] = {
    "ignore", "default", "all", "module", "once", "error", "", NULL
};
int storeW(char *val, void *data)
{
    const char *first;
    char *tail;
    int i;

    if (nW == MAXW) {
        fprintf(stderr, "-W options after number %d are ignored.\n", MAXW);
        return 0;
    }
    first = Wchoices[0];
    tail = strchr(val, ':');
    if (tail)
        *tail = 0;
    opt_store_choice_abbr(val, Wchoices);
    for (i = 0; Wchoices[i] != first; ++i)
        ;
    Wchoices[i] = Wchoices[0];
    Wchoices[0] = first;
    if (Wchoices[i][0]) {
        Wactions[nW] = i;
        Wtails[nW++] = tail ? tail + 1 : "";
    }
    else 
        fprintf(stderr, "Invalid -W option ignored: invalid action: '%s'\n",
                val);
    return 0;
}

struct opt_spec options[] = {
    {opt_text, OPT_NO_SF, OPT_NO_LF, OPT_NO_METAVAR,
     "Options and arguments (and corresponding environment variables):",
     OPT_NO_DATA},
    {opt_stop, "c", OPT_NO_LF, " cmd",
     "program passed in as string (terminates option list)", &scriptstr},
    {opt_store_1, "d", OPT_NO_LF, OPT_NO_METAVAR,
     "debug output from parser (also PYTHONDEBUG=x)", flags},
    {opt_store_1, "E", OPT_NO_LF, OPT_NO_METAVAR,
     "ignore environment variables (such as PYTHONPATH)", flags + 1},
    {opt_help, "h", OPT_NO_LF, OPT_NO_METAVAR, OPT_NO_HELP, OPT_NO_DATA},
    {opt_store_1, "i", OPT_NO_LF, OPT_NO_METAVAR,
     "inspect interactively after running script, (also PYTHONINSPECT=x)\n"
     "and force prompts, even if stdin does not appear to be a terminal",
     flags + 2},
    {opt_incr, "O", OPT_NO_LF, OPT_NO_METAVAR,
     "optimize generated bytecode (a tad; also PYTHONOPTIMIZE=x)",
     &opt_level},
    {opt_text, OPT_NO_SF, "-OO", OPT_NO_METAVAR,
     "remove doc-strings in addition to the -O optimizations", OPT_NO_DATA},
    {opt_store_choice, "Q", OPT_NO_LF, " arg",
     "division options: -Qold (default), -Qwarn, -Qwarnall, -Qnew",
     divchoices},
    {opt_store_1, "S", OPT_NO_LF, OPT_NO_METAVAR,
     "don't imply 'import site' on initialization", flags + 3},
    {opt_incr, "t", OPT_NO_LF, OPT_NO_METAVAR,
     "issue warnings about inconsistent tab usage (-tt: issue errors)",
     &tab_level},
    {opt_store_1, "u", OPT_NO_LF, OPT_NO_METAVAR,
     "unbuffered binary stdout and stderr (also PYTHONUNBUFFERED=x)\n"
     "see man page for details on internal buffering relating to '-u'",
     flags + 4},
    {opt_store_1, "v", OPT_NO_LF, OPT_NO_METAVAR,
     "verbose (trace import statements) (also PYTHONVERBOSE=x)", flags + 5},
    {opt_version, "V", OPT_NO_LF, OPT_NO_METAVAR,
     "print the Python version number and exit", "This is not Python 2.3.5"},
    {storeW, "W", OPT_NO_LF, " arg",
     "warning control (arg is action:message:category:module:lineno)",
     OPT_NO_DATA},
    {opt_store_1, "x", OPT_NO_LF, OPT_NO_METAVAR,
     "skip first line of source, allowing use of non-Unix forms of #!cmd",
     flags + 6},
    {opt_text, OPT_NO_SF, "file", OPT_NO_METAVAR,
     "program read from script file", OPT_NO_DATA},
    {opt_text, OPT_NO_SF, "-", OPT_NO_METAVAR,
     "program read from stdin (default; interactive mode if a tty)",
     OPT_NO_DATA},
    {opt_text, OPT_NO_SF, "arg ...", OPT_NO_METAVAR,
     "arguments passed to program in sys.argv[1:]", OPT_NO_DATA},
    {opt_text, OPT_NO_SF, OPT_NO_LF, OPT_NO_METAVAR,
     "Other environment variables:", ""},
    {opt_text, OPT_NO_SF, "PYTHONSTARTUP", OPT_NO_METAVAR,
     "file executed on interactive startup (no default)", OPT_NO_DATA},
    {opt_text, OPT_NO_SF, "PYTHONPATH", OPT_NO_METAVAR,
     "':'-separated list of directories prefixed to the\n"
     "default module search path.  The result is sys.path.", OPT_NO_DATA},
    {opt_text, OPT_NO_SF, "PYTHONHOME", OPT_NO_METAVAR,
     "alternate <prefix> directory (or <prefix>:<exec_prefix>).\n"
     "The default module search path uses <prefix>/pythonX.X.", OPT_NO_DATA},
    {opt_text, OPT_NO_SF, "PYTHONCASEOK", OPT_NO_METAVAR,
     "ignore case in 'import' statements (Windows).", OPT_NO_DATA},
    {OPT_NO_ACTION}
};

int main(int argc, char **argv)
{
    int i, j, nswitch = 0;
    const char *switches = "dEiSuvx";
    
    opt_basename(argv[0], '/');
    opt_config(0, 0, 0, ": ");
    opt_options1st();
    j = argc
        - opt_parse("usage: %s [option] ... [-c cmd | file | -] [arg] ...", 
                    options, argv);
    printf("switches turned on: ");
    for (i = 0; i < 7; ++i) {
        if (flags[i]) {
            putchar(switches[i]);
            ++nswitch;
        }
    }
    puts(nswitch ? "" : "none");
    printf("division option: %s\n", divchoices[0]);
    printf("optimization level: %d\n", opt_level);
    printf("tab warning level: %d\n", tab_level);
    printf("warning options:");
    if (nW) {
        putchar('\n');
        for (i = 0; i < nW; ++i)
            printf("  action: %-7s; tail: %s\n",
                   Wchoices[Wactions[i]], Wtails[i]);
    }
    else
        puts(" none");
    printf("script: ");
    if (scriptstr.s) {
        scriptstr.s[0] = scriptstr.s0;
        printf("string \"%s\"\n", scriptstr.s);
    }
    else if (j == argc || (argv[j][0] == '-' && !argv[j][1])) {
        puts("stdin");
        if (j < argc)
            ++j;
    }
    else
        printf("file '%s'\n", argv[j++]);
    printf("script arguments:");
    if (j == argc)
        puts(" none");
    else {
        putchar('\n');
        for ( ; j < argc; ++j)
            printf("  %s\n", argv[j]);
    }
    return 0;
}

