

BlockContext method!
value
	<primitive: 'BlockContext_value'>
!

BlockContext method!
value: arg
	<primitive: 'BlockContext_valueColon'>
!

BlockContext method!
value: arg1 value: arg2
	<primitive: 'BlockContext_value_value'>
!

BlockContext method!
value: arg1 value: arg2 value: arg3
	<primitive: 'BlockContext_value_value_value'>
!

BlockContext method!
valueWithArguments: anArray
	<primitive: 'BlockContext_valueWithArguments'>
!